### ISSUE TITLE
Allow reset subscription to current head ("END")

### ISSUE THREAD

**Issue by ovolynets** [zalando-nakadi/nakadi-ui#40]
I would like to be able to set the subscription to the current HEAD. Via API I can do it by specifying "END" as the offset value but it isn't available in the UI:

![image](https://user-images.githubusercontent.com/2162246/49943436-2b78b980-fee8-11e8-9c33-a192c71c5b9e.png)

**Comment by SergKam** [comment]
You can not "reset" subscription to "END" in Nakadi API. You can create subscription to the "END" but cannot reset to "END".
I created the ticket in Nakadi but will close this one.
