### ISSUE TITLE
Avoid confusion about available events for log-compacted event types

### ISSUE THREAD

**Issue by ePaul** [zalando-nakadi/nakadi-ui#42]
**Background**

The partitions overview for an event type shows a "total" number which is meant to indicate how many events are available currently in each partition.

The number is calculated as a difference between the "oldest" and "newest" offset.

For log-compacted event-types, not all events between those offsets are actually available – some might have been deleted because newer events with the same key superseded them. This means that the total number is just a rough estimate in this case.
(It is not feasible to calculate the actual number without actually traversing all events.)

This caused confusion in at least one case, where a total number of 16 M events was shown, but only 7M events could actually be consumed.

**Proposal**

For log-compacted events, show the number with a `≤` in front of it. (For "normal" event types, it should stay as it is right now.)
That way, it is immediately visible that there might be less events than that number available.

**Comment by SergKam** [comment]
Done
