### ISSUE TITLE
Add possibility to dryrun sql queries before creating a sql-event-type

### ISSUE THREAD

**Issue by pheanex** [zalando-nakadi/nakadi-ui#45]
Currently there is no convenient way of testing sql queries with nakadi-ui, as there is only curl (as documented here [nakadi-sql.docs](https://nakadi-sql.docs.zalando.net/reference/dryrun/#dry-run-a-query).
In order to make it easier to write nakadi sql-event-type-queries I'd like a way to do this via nakadi-ui (Maybe even in the /#createquery)

**Comment by SergKam** [comment]
Done
